# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

restclient:
  pool:
    backlog:
      base-url: https://fbm-flow-stage.melioffice.com
      socket-timeout: 10000
    planning-model-api:
      base-url: https://fbm-flow-stage.melioffice.com
      socket-timeout: 10000
    staffing-api:
      base-url: https://fbm-flow-stage.melioffice.com
      socket-timeout: 10000
